OK = 0
AUTHORIZATION_ERROR = 4401
PASSWORD_ERROR=4402
USER_NOT_EXIST=4403
PASSWORD_EMPTY_ERROR=4404
AUTHORITY_ERROR=4405

FUNCTION_NOT_FOND=4101
PARAM_ERROR=4102
NECESSARY_PARAM_ERROR=4103
PARAM_TYPE_ERROR=4104


DB_ERROR=4201

UNKNOWN_ERROR = 5555

CODE_MSG_MAP = {
    OK: 'ok',
    AUTHORIZATION_ERROR: '认证授权错误',
    UNKNOWN_ERROR: "未知错误",
    PASSWORD_ERROR: "密码错误",
    FUNCTION_NOT_FOND: "方法未找到！",
    USER_NOT_EXIST: "用户不存在！",
    PASSWORD_EMPTY_ERROR: "密码不可为空！！！",
    AUTHORITY_ERROR: "没有相关权限！",
    PARAM_ERROR: '请求参数错误',
    NECESSARY_PARAM_ERROR: "必要参数未填写！！",
    PARAM_TYPE_ERROR: "参数类型错误",
    DB_ERROR: '数据库错误',
    

}
